# Generated by Django 4.2.3 on 2023-07-22 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSubstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveSubstanceDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('more_information', models.CharField(max_length=150)),
                ('active_substances', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.activesubstance')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active_substances', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.activesubstance')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active_substances', models.ManyToManyField(related_name='active_substances', through='models.ActiveSubstanceDisease', to='models.activesubstance')),
            ],
        ),
        migrations.AddField(
            model_name='activesubstancedisease',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.disease'),
        ),
    ]
