# Generated by Django 4.2.3 on 2023-07-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='active_substances',
            field=models.ManyToManyField(related_name='disease_active_substances', through='models.ActiveSubstanceDisease', to='models.activesubstance'),
        ),
        migrations.RemoveField(
            model_name='drug',
            name='active_substances',
        ),
        migrations.AddField(
            model_name='drug',
            name='active_substances',
            field=models.ManyToManyField(related_name='drug_active_substances', to='models.activesubstance'),
        ),
    ]
