# Generated by Django 4.2.3 on 2023-07-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_disease_active_substances_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='active_substances',
            field=models.ManyToManyField(related_name='diseases', through='models.ActiveSubstanceDisease', to='models.activesubstance'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='active_substances',
            field=models.ManyToManyField(related_name='drugs', to='models.activesubstance'),
        ),
    ]
