# Generated by Django 4.2.3 on 2023-07-22 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_disease_active_substances_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activesubstancedisease',
            old_name='disease',
            new_name='diseases',
        ),
    ]
