# Generated by Django 4.2.3 on 2023-07-22 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_rename_disease_activesubstancedisease_diseases'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activesubstancedisease',
            old_name='active_substances',
            new_name='active_substance',
        ),
        migrations.RenameField(
            model_name='activesubstancedisease',
            old_name='diseases',
            new_name='disease',
        ),
    ]
