# Generated by Django 4.2.3 on 2023-07-22 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_rename_active_substances_activesubstancedisease_active_substance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='active_substances',
            new_name='active_substances2',
        ),
    ]
