# Generated by Django 4.2.3 on 2023-07-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_rename_active_substances_disease_active_substances2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='active_substances2',
        ),
        migrations.AddField(
            model_name='disease',
            name='active_substances',
            field=models.ManyToManyField(related_name='diseases', to='models.activesubstance'),
        ),
    ]
