# Generated by Django 4.2.3 on 2023-07-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_remove_disease_active_substances2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='active_substances',
        ),
        migrations.AddField(
            model_name='disease',
            name='active_substances2',
            field=models.ManyToManyField(related_name='diseases', through='models.ActiveSubstanceDisease', to='models.activesubstance'),
        ),
    ]
