# Generated by Django 4.2.3 on 2023-07-22 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_remove_disease_active_substances_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='active_substances2',
            new_name='active_substances',
        ),
    ]
